#!/bin/sh /etc/rc.common
# "new(er)" style init script
# Look at /lib/functions/service.sh on a running system for explanations of what other SERVICE_
# options you can use, and when you might want them.

USE_PROCD=1

START=11

PROG=/opt/hucon/i2c_led.sh

start_service() {
	if [ ! -z ${IPKG_INSTROOT+x} ];
		then echo "In build environment - doing nothing."; 
	else
		procd_open_instance 
		procd_set_param command "$PROG"
		procd_append_param command "on"
		procd_close_instance
	fi
}
